trigger:
  - develop
  - main

pool:
  name: Default

jobs:
- job: TestJob
  displayName: 'Ejecutar Pruebas E2E'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: |
      npm install
      npx playwright install
    displayName: 'Instalar dependencias'

  - script: |
      npm run test:e2e
    displayName: 'Ejecutar pruebas E2E'