trigger:
  - develop
  - main

pool:
  name: Default

jobs:
- job: TestJob
  displayName: 'Ejecutar Pruebas E2E'
  timeoutInMinutes: 10  # Añadir timeout al job
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: |
      npm ci --no-audit --no-fund
      npm install -g wait-on
    displayName: 'Instalar dependencias'

  - script: |
      npm install -D @playwright/test
      npx playwright install chromium --with-deps
    displayName: 'Instalar Playwright'

  - script: |
      start /B ng serve --configuration=development
      wait-on http://localhost:4200 -t 30000
      npx playwright test --project=chromium --workers=1
      taskkill /F /IM node.exe
    displayName: 'Ejecutar pruebas E2E'