trigger:
  - develop
  - main

pool:
  name: Default

jobs:
- job: TestJob
  displayName: 'Ejecutar Pruebas E2E'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: |
      npm ci
    displayName: 'Instalar dependencias'

  - script: |
      npm install -D @playwright/test
      npx playwright install --with-deps
    displayName: 'Instalar Playwright'

  - script: |
      start ng serve --configuration=development
      npx wait-on http://localhost:4200
      npx playwright test
    displayName: 'Ejecutar pruebas E2E'