trigger:
  - develop
  - main

pool:
  name: Default
  demands:
    - Agent.Name -equals FELIPECRUZ

jobs:
- job: TestJob
  displayName: 'Ejecutar Pruebas E2E'
  timeoutInMinutes: 15
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Instalar Node.js'
    retryCountOnTaskFailure: 3

  - powershell: |
      Get-Process -Name "node" -ErrorAction SilentlyContinue | Stop-Process -Force
      npm config set registry https://registry.npmjs.org/
      npm config set legacy-peer-deps true
      npm install --force
      npm ci --legacy-peer-deps
      npm install -g wait-on
    displayName: 'Instalar dependencias'
    timeoutInMinutes: 5
    continueOnError: false

  - script: |
      npm install -D @playwright/test --legacy-peer-deps
      npx playwright install chromium --with-deps
    displayName: 'Instalar Playwright'
    timeoutInMinutes: 5

  - powershell: |
      Get-Process -Name "node" -ErrorAction SilentlyContinue | Stop-Process -Force
      Start-Process -NoNewWindow npm -ArgumentList "start"
      Start-Sleep -Seconds 10
      npx wait-on http://localhost:4200 -t 60000
      npx playwright test --project=chromium --workers=1 --retries=2
      Get-Process -Name "node" -ErrorAction SilentlyContinue | Stop-Process -Force
    displayName: 'Ejecutar pruebas E2E'
    timeoutInMinutes: 10