trigger:
  - develop
  - main

pool:
  name: Default

jobs:
- job: TestJob
  displayName: 'Ejecutar Pruebas E2E'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: |
      npm ci
      npm install -g wait-on
    displayName: 'Instalar dependencias'

  - script: |
      npm install -D @playwright/test
      npx playwright install --with-deps
    displayName: 'Instalar Playwright'

  - script: |
      start /B ng serve --configuration=development
      timeout /t 30
      npx playwright test
      taskkill /F /IM node.exe
    displayName: 'Ejecutar pruebas E2E'