trigger:
  - develop
  - main

pool:
  name: Default
  demands:
    - npm
    - nodejs

jobs:
- job: TestJob
  displayName: 'Ejecutar Pruebas E2E'
  timeoutInMinutes: 10
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: |
      npm ci --no-audit --no-fund --prefer-offline
      npm install -g wait-on
    displayName: 'Instalar dependencias'
    timeoutInMinutes: 5

  - script: |
      npm install -D @playwright/test
      npx playwright install chromium --with-deps
    displayName: 'Instalar Playwright'
    timeoutInMinutes: 5

  - script: |
      start /B ng serve --configuration=development
      wait-on http://localhost:4200 -t 60000
      npx playwright test --project=chromium --workers=1 --retries=2 --timeout=30000
      taskkill /F /IM node.exe
    displayName: 'Ejecutar pruebas E2E'
    timeoutInMinutes: 10